# Generated by Django 2.2 on 2019-08-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('Description', models.TextField(max_length=500)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.District')),
            ],
        ),
    ]
